route-map ACCEPT-ALL permit 10

frr defaults traditional

hostname id-west-1

router bgp 65001
    bgp router-id 10.0.0.11

    neighbor 10.0.0.12 remote-as 65002
    neighbor 10.0.0.13 remote-as 65003

    address-family ipv4 unicast
        network 10.1.0.0/24
        network 10.100.0.0/24

        neighbor 10.0.0.12 activate
        neighbor 10.0.0.12 route-map ACCEPT-ALL in
        neighbor 10.0.0.12 route-map ACCEPT-ALL out
        
        neighbor 10.0.0.13 activate
        neighbor 10.0.0.13 route-map ACCEPT-ALL in
        neighbor 10.0.0.13 route-map ACCEPT-ALL out
    exit-address-family

ip route 10.1.0.0/24 Null0
ip route 10.100.0.0/24 Null0
