# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

release:
  replace_existing_artifacts: true

builds:
  - main: ./cmd/tunny
    binary: tunny

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

archives:
  - id: tunny
    formats:
      - tar.gz

    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    files:
      - src: .example.config.yaml
        dst: config.yaml

    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

nfpms:
  - id: tunny
    package_name: tunny
    vendor: Aldiwildan77
    homepage: https://github.com/Aldiwildan77/tunny
    maintainer: Aldiwildan77
    description: Route selected internet traffic through trusted nodes using TUN and SOCKS5.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./.example.config.yaml
        dst: /etc/tunny/config.yaml
        type: config

homebrew_casks:
  - name: tunny
    binaries:
      - tunny
    url:
      template: https://github.com/Aldiwildan77/tunny/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    repository:
      owner: Aldiwildan77
      name: tunny
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: https://github.com/Aldiwildan77/tunny
    description: Route selected internet traffic through trusted nodes using TUN and SOCKS5.

chocolateys:
  - name: tunny
    ids:
      - tunny
    title: Tunny
    authors: Aldiwildan77
    project_url: https://github.com/Aldiwildan77/tunny
    url_template: https://github.com/Aldiwildan77/tunny/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    icon_url: https://raw.githubusercontent.com/Aldiwildan77/tunny/master/logo.png
    license_url: https://github.com/Aldiwildan77/tunny/blob/master/LICENSE
    project_source_url: https://github.com/Aldiwildan77/tunny
    tags: network proxy vpn tun
    summary: Route selected internet traffic through trusted nodes.
    description: Route selected internet traffic through trusted nodes using TUN and SOCKS5.
    release_notes: https://github.com/Aldiwildan77/tunny/releases/tag/{{ .Tag }}
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: https://push.chocolatey.org/
    skip_publish: true
