# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunny" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "ad794bb5295f325a15f2917ec1879a49cd93fdd478b1d6338e37e068169a2890"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1984cf0da9901e165f2e521b59b8c05a1c95b03e2c6ea1130e821b3ec75b8422"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "66afa7a7fb7276d9808d51b8cc3978b280b2502a93fbaaa285b5017b722ce620"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1542fac8a80dc02f00945023cfd7496454073780ac77ca8cfc9ab6d86d5736b"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tunny"
  desc "Route selected internet traffic through trusted nodes using TUN and SOCKS5."
  homepage "https://github.com/Aldiwildan77/tunny"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunny"

  # No zap stanza required
end
