# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunny" do
  version "0.3.3"

  on_macos do
    on_arm do
      sha256 "932515e5630e1dac5082900031324871b5a9d6ae795bbbaf192a409a9ae2b2db"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_ #{version}_ darwin_ arm64.tar.gz"
    end
    on_intel do
      sha256 "53a7f27d1e89f8aeec37165b921f9a25ec10d46171812eb3d1e6b7ee92151a66"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_ #{version}_ darwin_ amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d6573104b7c560173d9f96fc0204518bb93dd42761ac132711f3cfc4ade15855"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_ #{version}_ linux_ arm64.tar.gz"
    end
    on_intel do
      sha256 "e678fbc6ac4224accaeab963a8ef654dc8c039907e800efa97a9313d3159772e"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_ #{version}_ linux_ amd64.tar.gz"
    end
  end

  name "tunny"
  desc "Route selected internet traffic through trusted nodes using TUN and SOCKS5."
  homepage "https://github.com/Aldiwildan77/tunny"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunny"

  # No zap stanza required
end
