# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunny" do
  version "0.3.4-rc-2"

  on_macos do
    on_arm do
      sha256 "20c00237e29f3064f0719a81b3891c7e5015ff3d85a531c371426d00a4d6dc4a"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d42c6357830b1e2b2b71d2a1d3180be5b855ab0102e2b0362f40eaf9d1c847f2"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "750d936b23dddf35c5c1327b1332def48ff7e02677c61d9d4360e353f6f2d081"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "704a6745fe1b83b3e3dfd34be2c7ac9b5eea39cbc77e71d198627b97eba743fc"
      url "https://github.com/Aldiwildan77/tunny/releases/download/v#{version}/tunny_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tunny"
  desc "Route selected internet traffic through trusted nodes using TUN and SOCKS5."
  homepage "https://github.com/Aldiwildan77/tunny"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunny"

  # No zap stanza required
end
