options => {
    listen => any
}

service_types => {
    tunny => {
        plugin => tcp_connect
        port => 7070

        interval => 3
        timeout => 1

        up_thresh => 2
        ok_thresh => 2
        down_thresh => 2
    }
}

plugins => {
    multifo => {
        up_thresh => 0.01
        ok_thresh => 0.01
        service_types => [ tunny ]

        tunny_pool => {
            id-west-1 => 10.0.0.11
            id-west-2 => 10.0.0.12
            id-west-3 => 10.0.0.13
        }
    }
}
