// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: control-plane/control.proto

package tunnycontrol

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_control_plane_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	NodeName          string                 `protobuf:"bytes,2,opt,name=node_name,proto3" json:"node_name,omitempty"`
	Transport         string                 `protobuf:"bytes,3,opt,name=transport,proto3" json:"transport,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,4,opt,name=uptime_seconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,5,opt,name=active_connections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_control_plane_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Status) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Status) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *Status) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Status) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_control_plane_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{2}
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_control_plane_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Route) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type RouteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteList) Reset() {
	*x = RouteList{}
	mi := &file_control_plane_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteList) ProtoMessage() {}

func (x *RouteList) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteList.ProtoReflect.Descriptor instead.
func (*RouteList) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{4}
}

func (x *RouteList) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type SetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRouteRequest) Reset() {
	*x = SetRouteRequest{}
	mi := &file_control_plane_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRouteRequest) ProtoMessage() {}

func (x *SetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRouteRequest.ProtoReflect.Descriptor instead.
func (*SetRouteRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{5}
}

func (x *SetRouteRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SetRouteRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type DeleteRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	mi := &file_control_plane_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRouteRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type DeleteRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteResponse) Reset() {
	*x = DeleteRouteResponse{}
	mi := &file_control_plane_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteResponse) ProtoMessage() {}

func (x *DeleteRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{7}
}

type ListProviderHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProviderHealthRequest) Reset() {
	*x = ListProviderHealthRequest{}
	mi := &file_control_plane_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProviderHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProviderHealthRequest) ProtoMessage() {}

func (x *ListProviderHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProviderHealthRequest.ProtoReflect.Descriptor instead.
func (*ListProviderHealthRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{8}
}

type ProviderHealth struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Provider             string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Address              string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	State                string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ConsecutiveFailures  int32                  `protobuf:"varint,4,opt,name=consecutive_failures,proto3" json:"consecutive_failures,omitempty"`
	ConsecutiveSuccesses int32                  `protobuf:"varint,5,opt,name=consecutive_successes,proto3" json:"consecutive_successes,omitempty"`
	LastCheckUnix        int64                  `protobuf:"varint,6,opt,name=last_check_unix,proto3" json:"last_check_unix,omitempty"`
	LastTransitionUnix   int64                  `protobuf:"varint,7,opt,name=last_transition_unix,proto3" json:"last_transition_unix,omitempty"`
	LastError            string                 `protobuf:"bytes,8,opt,name=last_error,proto3" json:"last_error,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProviderHealth) Reset() {
	*x = ProviderHealth{}
	mi := &file_control_plane_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealth) ProtoMessage() {}

func (x *ProviderHealth) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealth.ProtoReflect.Descriptor instead.
func (*ProviderHealth) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderHealth) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderHealth) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProviderHealth) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProviderHealth) GetConsecutiveFailures() int32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

func (x *ProviderHealth) GetConsecutiveSuccesses() int32 {
	if x != nil {
		return x.ConsecutiveSuccesses
	}
	return 0
}

func (x *ProviderHealth) GetLastCheckUnix() int64 {
	if x != nil {
		return x.LastCheckUnix
	}
	return 0
}

func (x *ProviderHealth) GetLastTransitionUnix() int64 {
	if x != nil {
		return x.LastTransitionUnix
	}
	return 0
}

func (x *ProviderHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ProviderHealthList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderHealth      `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderHealthList) Reset() {
	*x = ProviderHealthList{}
	mi := &file_control_plane_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealthList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealthList) ProtoMessage() {}

func (x *ProviderHealthList) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealthList.ProtoReflect.Descriptor instead.
func (*ProviderHealthList) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderHealthList) GetProviders() []*ProviderHealth {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_control_plane_control_proto protoreflect.FileDescriptor

const file_control_plane_control_proto_rawDesc = "" +
	"\n" +
	"\x1bcontrol-plane/control.proto\x12\x10tunny.control.v1\x1a\x1cgoogle/api/annotations.proto\"\x12\n" +
	"\x10GetStatusRequest\"\xb0\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1c\n" +
	"\tnode_name\x18\x02 \x01(\tR\tnode_name\x12\x1c\n" +
	"\ttransport\x18\x03 \x01(\tR\ttransport\x12&\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\x0euptime_seconds\x12.\n" +
	"\x12active_connections\x18\x05 \x01(\x03R\x12active_connections\"\x13\n" +
	"\x11ListRoutesRequest\"?\n" +
	"\x05Route\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"<\n" +
	"\tRouteList\x12/\n" +
	"\x06routes\x18\x01 \x03(\v2\x17.tunny.control.v1.RouteR\x06routes\"I\n" +
	"\x0fSetRouteRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"0\n" +
	"\x12DeleteRouteRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\x15\n" +
	"\x13DeleteRouteResponse\"\x1b\n" +
	"\x19ListProviderHealthRequest\"\xc4\x02\n" +
	"\x0eProviderHealth\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x122\n" +
	"\x14consecutive_failures\x18\x04 \x01(\x05R\x14consecutive_failures\x124\n" +
	"\x15consecutive_successes\x18\x05 \x01(\x05R\x15consecutive_successes\x12(\n" +
	"\x0flast_check_unix\x18\x06 \x01(\x03R\x0flast_check_unix\x122\n" +
	"\x14last_transition_unix\x18\a \x01(\x03R\x14last_transition_unix\x12\x1e\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\n" +
	"last_error\"T\n" +
	"\x12ProviderHealthList\x12>\n" +
	"\tproviders\x18\x01 \x03(\v2 .tunny.control.v1.ProviderHealthR\tproviders2\xb3\x04\n" +
	"\fControlPlane\x12]\n" +
	"\tGetStatus\x12\".tunny.control.v1.GetStatusRequest\x1a\x18.tunny.control.v1.Status\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/status\x12b\n" +
	"\n" +
	"ListRoutes\x12#.tunny.control.v1.ListRoutesRequest\x1a\x1b.tunny.control.v1.RouteList\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/routes\x12]\n" +
	"\bSetRoute\x12!.tunny.control.v1.SetRouteRequest\x1a\x17.tunny.control.v1.Route\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/routes\x12y\n" +
	"\vDeleteRoute\x12$.tunny.control.v1.DeleteRouteRequest\x1a%.tunny.control.v1.DeleteRouteResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/routes/{hostname}\x12\x85\x01\n" +
	"\x12ListProviderHealth\x12+.tunny.control.v1.ListProviderHealthRequest\x1a$.tunny.control.v1.ProviderHealthList\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/providers/healthBKZIgithub.com/Aldiwildan77/tunny/control-plane/gen/tunnycontrol;tunnycontrolb\x06proto3"

var (
	file_control_plane_control_proto_rawDescOnce sync.Once
	file_control_plane_control_proto_rawDescData []byte
)

func file_control_plane_control_proto_rawDescGZIP() []byte {
	file_control_plane_control_proto_rawDescOnce.Do(func() {
		file_control_plane_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_plane_control_proto_rawDesc), len(file_control_plane_control_proto_rawDesc)))
	})
	return file_control_plane_control_proto_rawDescData
}

var file_control_plane_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_control_plane_control_proto_goTypes = []any{
	(*GetStatusRequest)(nil),          // 0: tunny.control.v1.GetStatusRequest
	(*Status)(nil),                    // 1: tunny.control.v1.Status
	(*ListRoutesRequest)(nil),         // 2: tunny.control.v1.ListRoutesRequest
	(*Route)(nil),                     // 3: tunny.control.v1.Route
	(*RouteList)(nil),                 // 4: tunny.control.v1.RouteList
	(*SetRouteRequest)(nil),           // 5: tunny.control.v1.SetRouteRequest
	(*DeleteRouteRequest)(nil),        // 6: tunny.control.v1.DeleteRouteRequest
	(*DeleteRouteResponse)(nil),       // 7: tunny.control.v1.DeleteRouteResponse
	(*ListProviderHealthRequest)(nil), // 8: tunny.control.v1.ListProviderHealthRequest
	(*ProviderHealth)(nil),            // 9: tunny.control.v1.ProviderHealth
	(*ProviderHealthList)(nil),        // 10: tunny.control.v1.ProviderHealthList
}
var file_control_plane_control_proto_depIdxs = []int32{
	3,  // 0: tunny.control.v1.RouteList.routes:type_name -> tunny.control.v1.Route
	9,  // 1: tunny.control.v1.ProviderHealthList.providers:type_name -> tunny.control.v1.ProviderHealth
	0,  // 2: tunny.control.v1.ControlPlane.GetStatus:input_type -> tunny.control.v1.GetStatusRequest
	2,  // 3: tunny.control.v1.ControlPlane.ListRoutes:input_type -> tunny.control.v1.ListRoutesRequest
	5,  // 4: tunny.control.v1.ControlPlane.SetRoute:input_type -> tunny.control.v1.SetRouteRequest
	6,  // 5: tunny.control.v1.ControlPlane.DeleteRoute:input_type -> tunny.control.v1.DeleteRouteRequest
	8,  // 6: tunny.control.v1.ControlPlane.ListProviderHealth:input_type -> tunny.control.v1.ListProviderHealthRequest
	1,  // 7: tunny.control.v1.ControlPlane.GetStatus:output_type -> tunny.control.v1.Status
	4,  // 8: tunny.control.v1.ControlPlane.ListRoutes:output_type -> tunny.control.v1.RouteList
	3,  // 9: tunny.control.v1.ControlPlane.SetRoute:output_type -> tunny.control.v1.Route
	7,  // 10: tunny.control.v1.ControlPlane.DeleteRoute:output_type -> tunny.control.v1.DeleteRouteResponse
	10, // 11: tunny.control.v1.ControlPlane.ListProviderHealth:output_type -> tunny.control.v1.ProviderHealthList
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_control_plane_control_proto_init() }
func file_control_plane_control_proto_init() {
	if File_control_plane_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_plane_control_proto_rawDesc), len(file_control_plane_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_control_proto_goTypes,
		DependencyIndexes: file_control_plane_control_proto_depIdxs,
		MessageInfos:      file_control_plane_control_proto_msgTypes,
	}.Build()
	File_control_plane_control_proto = out.File
	file_control_plane_control_proto_goTypes = nil
	file_control_plane_control_proto_depIdxs = nil
}
