// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: control-plane/control.proto

package tunnycontrol

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_control_plane_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{0}
}

type Status struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	NodeName          string                 `protobuf:"bytes,2,opt,name=node_name,proto3" json:"node_name,omitempty"`
	Transport         string                 `protobuf:"bytes,3,opt,name=transport,proto3" json:"transport,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,4,opt,name=uptime_seconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,5,opt,name=active_connections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_control_plane_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Status) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Status) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *Status) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Status) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_control_plane_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{2}
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_control_plane_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Route) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type RouteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteList) Reset() {
	*x = RouteList{}
	mi := &file_control_plane_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteList) ProtoMessage() {}

func (x *RouteList) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteList.ProtoReflect.Descriptor instead.
func (*RouteList) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{4}
}

func (x *RouteList) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type SetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRouteRequest) Reset() {
	*x = SetRouteRequest{}
	mi := &file_control_plane_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRouteRequest) ProtoMessage() {}

func (x *SetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRouteRequest.ProtoReflect.Descriptor instead.
func (*SetRouteRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{5}
}

func (x *SetRouteRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SetRouteRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type DeleteRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	mi := &file_control_plane_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRouteRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type DeleteRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteResponse) Reset() {
	*x = DeleteRouteResponse{}
	mi := &file_control_plane_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteResponse) ProtoMessage() {}

func (x *DeleteRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_control_proto_rawDescGZIP(), []int{7}
}

var File_control_plane_control_proto protoreflect.FileDescriptor

const file_control_plane_control_proto_rawDesc = "" +
	"\n" +
	"\x1bcontrol-plane/control.proto\x12\x10tunny.control.v1\x1a\x1cgoogle/api/annotations.proto\"\x12\n" +
	"\x10GetStatusRequest\"\xb0\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1c\n" +
	"\tnode_name\x18\x02 \x01(\tR\tnode_name\x12\x1c\n" +
	"\ttransport\x18\x03 \x01(\tR\ttransport\x12&\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\x0euptime_seconds\x12.\n" +
	"\x12active_connections\x18\x05 \x01(\x03R\x12active_connections\"\x13\n" +
	"\x11ListRoutesRequest\"?\n" +
	"\x05Route\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"<\n" +
	"\tRouteList\x12/\n" +
	"\x06routes\x18\x01 \x03(\v2\x17.tunny.control.v1.RouteR\x06routes\"I\n" +
	"\x0fSetRouteRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"0\n" +
	"\x12DeleteRouteRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\x15\n" +
	"\x13DeleteRouteResponse2\xab\x03\n" +
	"\fControlPlane\x12]\n" +
	"\tGetStatus\x12\".tunny.control.v1.GetStatusRequest\x1a\x18.tunny.control.v1.Status\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/status\x12b\n" +
	"\n" +
	"ListRoutes\x12#.tunny.control.v1.ListRoutesRequest\x1a\x1b.tunny.control.v1.RouteList\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/routes\x12]\n" +
	"\bSetRoute\x12!.tunny.control.v1.SetRouteRequest\x1a\x17.tunny.control.v1.Route\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/routes\x12y\n" +
	"\vDeleteRoute\x12$.tunny.control.v1.DeleteRouteRequest\x1a%.tunny.control.v1.DeleteRouteResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/routes/{hostname}BKZIgithub.com/Aldiwildan77/tunny/control-plane/gen/tunnycontrol;tunnycontrolb\x06proto3"

var (
	file_control_plane_control_proto_rawDescOnce sync.Once
	file_control_plane_control_proto_rawDescData []byte
)

func file_control_plane_control_proto_rawDescGZIP() []byte {
	file_control_plane_control_proto_rawDescOnce.Do(func() {
		file_control_plane_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_plane_control_proto_rawDesc), len(file_control_plane_control_proto_rawDesc)))
	})
	return file_control_plane_control_proto_rawDescData
}

var file_control_plane_control_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_control_plane_control_proto_goTypes = []any{
	(*GetStatusRequest)(nil),    // 0: tunny.control.v1.GetStatusRequest
	(*Status)(nil),              // 1: tunny.control.v1.Status
	(*ListRoutesRequest)(nil),   // 2: tunny.control.v1.ListRoutesRequest
	(*Route)(nil),               // 3: tunny.control.v1.Route
	(*RouteList)(nil),           // 4: tunny.control.v1.RouteList
	(*SetRouteRequest)(nil),     // 5: tunny.control.v1.SetRouteRequest
	(*DeleteRouteRequest)(nil),  // 6: tunny.control.v1.DeleteRouteRequest
	(*DeleteRouteResponse)(nil), // 7: tunny.control.v1.DeleteRouteResponse
}
var file_control_plane_control_proto_depIdxs = []int32{
	3, // 0: tunny.control.v1.RouteList.routes:type_name -> tunny.control.v1.Route
	0, // 1: tunny.control.v1.ControlPlane.GetStatus:input_type -> tunny.control.v1.GetStatusRequest
	2, // 2: tunny.control.v1.ControlPlane.ListRoutes:input_type -> tunny.control.v1.ListRoutesRequest
	5, // 3: tunny.control.v1.ControlPlane.SetRoute:input_type -> tunny.control.v1.SetRouteRequest
	6, // 4: tunny.control.v1.ControlPlane.DeleteRoute:input_type -> tunny.control.v1.DeleteRouteRequest
	1, // 5: tunny.control.v1.ControlPlane.GetStatus:output_type -> tunny.control.v1.Status
	4, // 6: tunny.control.v1.ControlPlane.ListRoutes:output_type -> tunny.control.v1.RouteList
	3, // 7: tunny.control.v1.ControlPlane.SetRoute:output_type -> tunny.control.v1.Route
	7, // 8: tunny.control.v1.ControlPlane.DeleteRoute:output_type -> tunny.control.v1.DeleteRouteResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_control_plane_control_proto_init() }
func file_control_plane_control_proto_init() {
	if File_control_plane_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_plane_control_proto_rawDesc), len(file_control_plane_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_control_proto_goTypes,
		DependencyIndexes: file_control_plane_control_proto_depIdxs,
		MessageInfos:      file_control_plane_control_proto_msgTypes,
	}.Build()
	File_control_plane_control_proto = out.File
	file_control_plane_control_proto_goTypes = nil
	file_control_plane_control_proto_depIdxs = nil
}
